name: 'Generate cross check inventory on cross check change'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
